version: '1.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      XPACK_MONITORING_ENABLED: false
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx256m -XMs256m"
      discovery.type: single-node
      network.host: "0.0.0.0"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    restart: always
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - D:/bidding-system/logAggregation/elk/logstash/config:/etc/logstash/conf.d/
    ports:
      - "9999:9999"
    depends_on:
      - elasticsearch

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - logstash
